/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentAddDTO
 */
export interface CommentAddDTO {
    /**
     * 
     * @type {string}
     * @memberof CommentAddDTO
     */
    text: string;
    /**
     * 
     * @type {string}
     * @memberof CommentAddDTO
     */
    torrentId: string;
}

/**
 * Check if a given object implements the CommentAddDTO interface.
 */
export function instanceOfCommentAddDTO(value: object): value is CommentAddDTO {
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('torrentId' in value) || value['torrentId'] === undefined) return false;
    return true;
}

export function CommentAddDTOFromJSON(json: any): CommentAddDTO {
    return CommentAddDTOFromJSONTyped(json, false);
}

export function CommentAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentAddDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
        'torrentId': json['torrentId'],
    };
}

export function CommentAddDTOToJSON(json: any): CommentAddDTO {
    return CommentAddDTOToJSONTyped(json, false);
}

export function CommentAddDTOToJSONTyped(value?: CommentAddDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'torrentId': value['torrentId'],
    };
}

