/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TorrentDTO } from './TorrentDTO';
import {
    TorrentDTOFromJSON,
    TorrentDTOFromJSONTyped,
    TorrentDTOToJSON,
    TorrentDTOToJSONTyped,
} from './TorrentDTO';
import type { UserDTO } from './UserDTO';
import {
    UserDTOFromJSON,
    UserDTOFromJSONTyped,
    UserDTOToJSON,
    UserDTOToJSONTyped,
} from './UserDTO';

/**
 * 
 * @export
 * @interface CommentDTO
 */
export interface CommentDTO {
    /**
     * 
     * @type {string}
     * @memberof CommentDTO
     */
    id: string;
    /**
     * 
     * @type {UserDTO}
     * @memberof CommentDTO
     */
    user: UserDTO;
    /**
     * 
     * @type {TorrentDTO}
     * @memberof CommentDTO
     */
    torrent: TorrentDTO;
    /**
     * 
     * @type {Date}
     * @memberof CommentDTO
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof CommentDTO
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof CommentDTO
     */
    text: string;
}

/**
 * Check if a given object implements the CommentDTO interface.
 */
export function instanceOfCommentDTO(value: object): value is CommentDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('torrent' in value) || value['torrent'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function CommentDTOFromJSON(json: any): CommentDTO {
    return CommentDTOFromJSONTyped(json, false);
}

export function CommentDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'user': UserDTOFromJSON(json['user']),
        'torrent': TorrentDTOFromJSON(json['torrent']),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'text': json['text'],
    };
}

export function CommentDTOToJSON(json: any): CommentDTO {
    return CommentDTOToJSONTyped(json, false);
}

export function CommentDTOToJSONTyped(value?: CommentDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user': UserDTOToJSON(value['user']),
        'torrent': TorrentDTOToJSON(value['torrent']),
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
        'text': value['text'],
    };
}

