/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FeedbackSatisfactionEnum } from './FeedbackSatisfactionEnum';
import {
    FeedbackSatisfactionEnumFromJSON,
    FeedbackSatisfactionEnumFromJSONTyped,
    FeedbackSatisfactionEnumToJSON,
    FeedbackSatisfactionEnumToJSONTyped,
} from './FeedbackSatisfactionEnum';
import type { UserDTO } from './UserDTO';
import {
    UserDTOFromJSON,
    UserDTOFromJSONTyped,
    UserDTOToJSON,
    UserDTOToJSONTyped,
} from './UserDTO';

/**
 * 
 * @export
 * @interface FeedbackDTO
 */
export interface FeedbackDTO {
    /**
     * 
     * @type {string}
     * @memberof FeedbackDTO
     */
    id: string;
    /**
     * 
     * @type {UserDTO}
     * @memberof FeedbackDTO
     */
    user: UserDTO;
    /**
     * 
     * @type {Date}
     * @memberof FeedbackDTO
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof FeedbackDTO
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof FeedbackDTO
     */
    text: string;
    /**
     * 
     * @type {FeedbackSatisfactionEnum}
     * @memberof FeedbackDTO
     */
    satisfaction: FeedbackSatisfactionEnum;
    /**
     * 
     * @type {boolean}
     * @memberof FeedbackDTO
     */
    wouldRecommend: boolean;
}



/**
 * Check if a given object implements the FeedbackDTO interface.
 */
export function instanceOfFeedbackDTO(value: object): value is FeedbackDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('satisfaction' in value) || value['satisfaction'] === undefined) return false;
    if (!('wouldRecommend' in value) || value['wouldRecommend'] === undefined) return false;
    return true;
}

export function FeedbackDTOFromJSON(json: any): FeedbackDTO {
    return FeedbackDTOFromJSONTyped(json, false);
}

export function FeedbackDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'user': UserDTOFromJSON(json['user']),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'text': json['text'],
        'satisfaction': FeedbackSatisfactionEnumFromJSON(json['satisfaction']),
        'wouldRecommend': json['wouldRecommend'],
    };
}

export function FeedbackDTOToJSON(json: any): FeedbackDTO {
    return FeedbackDTOToJSONTyped(json, false);
}

export function FeedbackDTOToJSONTyped(value?: FeedbackDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user': UserDTOToJSON(value['user']),
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
        'text': value['text'],
        'satisfaction': FeedbackSatisfactionEnumToJSON(value['satisfaction']),
        'wouldRecommend': value['wouldRecommend'],
    };
}

