/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FeedbackSatisfactionEnum } from './FeedbackSatisfactionEnum';
import {
    FeedbackSatisfactionEnumFromJSON,
    FeedbackSatisfactionEnumFromJSONTyped,
    FeedbackSatisfactionEnumToJSON,
    FeedbackSatisfactionEnumToJSONTyped,
} from './FeedbackSatisfactionEnum';

/**
 * 
 * @export
 * @interface FeedbackAddDTO
 */
export interface FeedbackAddDTO {
    /**
     * 
     * @type {string}
     * @memberof FeedbackAddDTO
     */
    text: string;
    /**
     * 
     * @type {FeedbackSatisfactionEnum}
     * @memberof FeedbackAddDTO
     */
    satisfaction: FeedbackSatisfactionEnum;
    /**
     * 
     * @type {boolean}
     * @memberof FeedbackAddDTO
     */
    wouldRecommend: boolean;
}



/**
 * Check if a given object implements the FeedbackAddDTO interface.
 */
export function instanceOfFeedbackAddDTO(value: object): value is FeedbackAddDTO {
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('satisfaction' in value) || value['satisfaction'] === undefined) return false;
    if (!('wouldRecommend' in value) || value['wouldRecommend'] === undefined) return false;
    return true;
}

export function FeedbackAddDTOFromJSON(json: any): FeedbackAddDTO {
    return FeedbackAddDTOFromJSONTyped(json, false);
}

export function FeedbackAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackAddDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
        'satisfaction': FeedbackSatisfactionEnumFromJSON(json['satisfaction']),
        'wouldRecommend': json['wouldRecommend'],
    };
}

export function FeedbackAddDTOToJSON(json: any): FeedbackAddDTO {
    return FeedbackAddDTOToJSONTyped(json, false);
}

export function FeedbackAddDTOToJSONTyped(value?: FeedbackAddDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'satisfaction': FeedbackSatisfactionEnumToJSON(value['satisfaction']),
        'wouldRecommend': value['wouldRecommend'],
    };
}

