/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FeedbackDTO } from './FeedbackDTO';
import {
    FeedbackDTOFromJSON,
    FeedbackDTOFromJSONTyped,
    FeedbackDTOToJSON,
    FeedbackDTOToJSONTyped,
} from './FeedbackDTO';

/**
 * 
 * @export
 * @interface FeedbackDTOPagedResponse
 */
export interface FeedbackDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof FeedbackDTOPagedResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof FeedbackDTOPagedResponse
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof FeedbackDTOPagedResponse
     */
    totalCount: number;
    /**
     * 
     * @type {Array<FeedbackDTO>}
     * @memberof FeedbackDTOPagedResponse
     */
    data: Array<FeedbackDTO>;
}

/**
 * Check if a given object implements the FeedbackDTOPagedResponse interface.
 */
export function instanceOfFeedbackDTOPagedResponse(value: object): value is FeedbackDTOPagedResponse {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function FeedbackDTOPagedResponseFromJSON(json: any): FeedbackDTOPagedResponse {
    return FeedbackDTOPagedResponseFromJSONTyped(json, false);
}

export function FeedbackDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackDTOPagedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(FeedbackDTOFromJSON)),
    };
}

export function FeedbackDTOPagedResponseToJSON(json: any): FeedbackDTOPagedResponse {
    return FeedbackDTOPagedResponseToJSONTyped(json, false);
}

export function FeedbackDTOPagedResponseToJSONTyped(value?: FeedbackDTOPagedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': ((value['data'] as Array<any>).map(FeedbackDTOToJSON)),
    };
}

