/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FeedbackSatisfactionEnum = {
    VeryHappy: 'VeryHappy',
    Happy: 'Happy',
    Neutral: 'Neutral',
    Unhappy: 'Unhappy'
} as const;
export type FeedbackSatisfactionEnum = typeof FeedbackSatisfactionEnum[keyof typeof FeedbackSatisfactionEnum];


export function instanceOfFeedbackSatisfactionEnum(value: any): boolean {
    for (const key in FeedbackSatisfactionEnum) {
        if (Object.prototype.hasOwnProperty.call(FeedbackSatisfactionEnum, key)) {
            if (FeedbackSatisfactionEnum[key as keyof typeof FeedbackSatisfactionEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FeedbackSatisfactionEnumFromJSON(json: any): FeedbackSatisfactionEnum {
    return FeedbackSatisfactionEnumFromJSONTyped(json, false);
}

export function FeedbackSatisfactionEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackSatisfactionEnum {
    return json as FeedbackSatisfactionEnum;
}

export function FeedbackSatisfactionEnumToJSON(value?: FeedbackSatisfactionEnum | null): any {
    return value as any;
}

export function FeedbackSatisfactionEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): FeedbackSatisfactionEnum {
    return value as FeedbackSatisfactionEnum;
}

