/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvitationDTO } from './InvitationDTO';
import {
    InvitationDTOFromJSON,
    InvitationDTOFromJSONTyped,
    InvitationDTOToJSON,
    InvitationDTOToJSONTyped,
} from './InvitationDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface InvitationDTORequestResponse
 */
export interface InvitationDTORequestResponse {
    /**
     * 
     * @type {InvitationDTO}
     * @memberof InvitationDTORequestResponse
     */
    readonly response?: InvitationDTO | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof InvitationDTORequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the InvitationDTORequestResponse interface.
 */
export function instanceOfInvitationDTORequestResponse(value: object): value is InvitationDTORequestResponse {
    return true;
}

export function InvitationDTORequestResponseFromJSON(json: any): InvitationDTORequestResponse {
    return InvitationDTORequestResponseFromJSONTyped(json, false);
}

export function InvitationDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvitationDTORequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : InvitationDTOFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function InvitationDTORequestResponseToJSON(json: any): InvitationDTORequestResponse {
    return InvitationDTORequestResponseToJSONTyped(json, false);
}

export function InvitationDTORequestResponseToJSONTyped(value?: Omit<InvitationDTORequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

