/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvitationDTO } from './InvitationDTO';
import {
    InvitationDTOFromJSON,
    InvitationDTOFromJSONTyped,
    InvitationDTOToJSON,
    InvitationDTOToJSONTyped,
} from './InvitationDTO';

/**
 * 
 * @export
 * @interface InvitationDTOPagedResponse
 */
export interface InvitationDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof InvitationDTOPagedResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof InvitationDTOPagedResponse
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof InvitationDTOPagedResponse
     */
    totalCount: number;
    /**
     * 
     * @type {Array<InvitationDTO>}
     * @memberof InvitationDTOPagedResponse
     */
    data: Array<InvitationDTO>;
}

/**
 * Check if a given object implements the InvitationDTOPagedResponse interface.
 */
export function instanceOfInvitationDTOPagedResponse(value: object): value is InvitationDTOPagedResponse {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function InvitationDTOPagedResponseFromJSON(json: any): InvitationDTOPagedResponse {
    return InvitationDTOPagedResponseFromJSONTyped(json, false);
}

export function InvitationDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvitationDTOPagedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(InvitationDTOFromJSON)),
    };
}

export function InvitationDTOPagedResponseToJSON(json: any): InvitationDTOPagedResponse {
    return InvitationDTOPagedResponseToJSONTyped(json, false);
}

export function InvitationDTOPagedResponseToJSONTyped(value?: InvitationDTOPagedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': ((value['data'] as Array<any>).map(InvitationDTOToJSON)),
    };
}

