/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvitationDTOPagedResponse } from './InvitationDTOPagedResponse';
import {
    InvitationDTOPagedResponseFromJSON,
    InvitationDTOPagedResponseFromJSONTyped,
    InvitationDTOPagedResponseToJSON,
    InvitationDTOPagedResponseToJSONTyped,
} from './InvitationDTOPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface InvitationDTOPagedResponseRequestResponse
 */
export interface InvitationDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {InvitationDTOPagedResponse}
     * @memberof InvitationDTOPagedResponseRequestResponse
     */
    readonly response?: InvitationDTOPagedResponse | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof InvitationDTOPagedResponseRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the InvitationDTOPagedResponseRequestResponse interface.
 */
export function instanceOfInvitationDTOPagedResponseRequestResponse(value: object): value is InvitationDTOPagedResponseRequestResponse {
    return true;
}

export function InvitationDTOPagedResponseRequestResponseFromJSON(json: any): InvitationDTOPagedResponseRequestResponse {
    return InvitationDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function InvitationDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvitationDTOPagedResponseRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : InvitationDTOPagedResponseFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function InvitationDTOPagedResponseRequestResponseToJSON(json: any): InvitationDTOPagedResponseRequestResponse {
    return InvitationDTOPagedResponseRequestResponseToJSONTyped(json, false);
}

export function InvitationDTOPagedResponseRequestResponseToJSONTyped(value?: Omit<InvitationDTOPagedResponseRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

