/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserDTO } from './UserDTO';
import {
    UserDTOFromJSON,
    UserDTOFromJSONTyped,
    UserDTOToJSON,
    UserDTOToJSONTyped,
} from './UserDTO';

/**
 * 
 * @export
 * @interface InvitationDTO
 */
export interface InvitationDTO {
    /**
     * 
     * @type {string}
     * @memberof InvitationDTO
     */
    id: string;
    /**
     * 
     * @type {UserDTO}
     * @memberof InvitationDTO
     */
    createdUser?: UserDTO | null;
    /**
     * 
     * @type {UserDTO}
     * @memberof InvitationDTO
     */
    generatedByUser: UserDTO;
    /**
     * 
     * @type {Date}
     * @memberof InvitationDTO
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof InvitationDTO
     */
    updatedAt: Date;
    /**
     * 
     * @type {boolean}
     * @memberof InvitationDTO
     */
    used: boolean;
}

/**
 * Check if a given object implements the InvitationDTO interface.
 */
export function instanceOfInvitationDTO(value: object): value is InvitationDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('generatedByUser' in value) || value['generatedByUser'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('used' in value) || value['used'] === undefined) return false;
    return true;
}

export function InvitationDTOFromJSON(json: any): InvitationDTO {
    return InvitationDTOFromJSONTyped(json, false);
}

export function InvitationDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvitationDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdUser': json['createdUser'] == null ? undefined : UserDTOFromJSON(json['createdUser']),
        'generatedByUser': UserDTOFromJSON(json['generatedByUser']),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'used': json['used'],
    };
}

export function InvitationDTOToJSON(json: any): InvitationDTO {
    return InvitationDTOToJSONTyped(json, false);
}

export function InvitationDTOToJSONTyped(value?: InvitationDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createdUser': UserDTOToJSON(value['createdUser']),
        'generatedByUser': UserDTOToJSON(value['generatedByUser']),
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
        'used': value['used'],
    };
}

