/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';
import type { LikeCheckResponseDTO } from './LikeCheckResponseDTO';
import {
    LikeCheckResponseDTOFromJSON,
    LikeCheckResponseDTOFromJSONTyped,
    LikeCheckResponseDTOToJSON,
    LikeCheckResponseDTOToJSONTyped,
} from './LikeCheckResponseDTO';

/**
 * 
 * @export
 * @interface LikeCheckResponseDTORequestResponse
 */
export interface LikeCheckResponseDTORequestResponse {
    /**
     * 
     * @type {LikeCheckResponseDTO}
     * @memberof LikeCheckResponseDTORequestResponse
     */
    readonly response?: LikeCheckResponseDTO | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof LikeCheckResponseDTORequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the LikeCheckResponseDTORequestResponse interface.
 */
export function instanceOfLikeCheckResponseDTORequestResponse(value: object): value is LikeCheckResponseDTORequestResponse {
    return true;
}

export function LikeCheckResponseDTORequestResponseFromJSON(json: any): LikeCheckResponseDTORequestResponse {
    return LikeCheckResponseDTORequestResponseFromJSONTyped(json, false);
}

export function LikeCheckResponseDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LikeCheckResponseDTORequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : LikeCheckResponseDTOFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function LikeCheckResponseDTORequestResponseToJSON(json: any): LikeCheckResponseDTORequestResponse {
    return LikeCheckResponseDTORequestResponseToJSONTyped(json, false);
}

export function LikeCheckResponseDTORequestResponseToJSONTyped(value?: Omit<LikeCheckResponseDTORequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

