/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LikeCheckResponseDTO
 */
export interface LikeCheckResponseDTO {
    /**
     * 
     * @type {boolean}
     * @memberof LikeCheckResponseDTO
     */
    isLiked: boolean;
}

/**
 * Check if a given object implements the LikeCheckResponseDTO interface.
 */
export function instanceOfLikeCheckResponseDTO(value: object): value is LikeCheckResponseDTO {
    if (!('isLiked' in value) || value['isLiked'] === undefined) return false;
    return true;
}

export function LikeCheckResponseDTOFromJSON(json: any): LikeCheckResponseDTO {
    return LikeCheckResponseDTOFromJSONTyped(json, false);
}

export function LikeCheckResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): LikeCheckResponseDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'isLiked': json['isLiked'],
    };
}

export function LikeCheckResponseDTOToJSON(json: any): LikeCheckResponseDTO {
    return LikeCheckResponseDTOToJSONTyped(json, false);
}

export function LikeCheckResponseDTOToJSONTyped(value?: LikeCheckResponseDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isLiked': value['isLiked'],
    };
}

