/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TorrentDTOPagedResponse } from './TorrentDTOPagedResponse';
import {
    TorrentDTOPagedResponseFromJSON,
    TorrentDTOPagedResponseFromJSONTyped,
    TorrentDTOPagedResponseToJSON,
    TorrentDTOPagedResponseToJSONTyped,
} from './TorrentDTOPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface TorrentDTOPagedResponseRequestResponse
 */
export interface TorrentDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {TorrentDTOPagedResponse}
     * @memberof TorrentDTOPagedResponseRequestResponse
     */
    readonly response?: TorrentDTOPagedResponse | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof TorrentDTOPagedResponseRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the TorrentDTOPagedResponseRequestResponse interface.
 */
export function instanceOfTorrentDTOPagedResponseRequestResponse(value: object): value is TorrentDTOPagedResponseRequestResponse {
    return true;
}

export function TorrentDTOPagedResponseRequestResponseFromJSON(json: any): TorrentDTOPagedResponseRequestResponse {
    return TorrentDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function TorrentDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TorrentDTOPagedResponseRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : TorrentDTOPagedResponseFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function TorrentDTOPagedResponseRequestResponseToJSON(json: any): TorrentDTOPagedResponseRequestResponse {
    return TorrentDTOPagedResponseRequestResponseToJSONTyped(json, false);
}

export function TorrentDTOPagedResponseRequestResponseToJSONTyped(value?: Omit<TorrentDTOPagedResponseRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

