/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserDTO } from './UserDTO';
import {
    UserDTOFromJSON,
    UserDTOFromJSONTyped,
    UserDTOToJSON,
    UserDTOToJSONTyped,
} from './UserDTO';

/**
 * 
 * @export
 * @interface TorrentDTO
 */
export interface TorrentDTO {
    /**
     * 
     * @type {string}
     * @memberof TorrentDTO
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TorrentDTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TorrentDTO
     */
    description?: string | null;
    /**
     * 
     * @type {UserDTO}
     * @memberof TorrentDTO
     */
    user: UserDTO;
    /**
     * 
     * @type {number}
     * @memberof TorrentDTO
     */
    likes: number;
    /**
     * 
     * @type {Date}
     * @memberof TorrentDTO
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof TorrentDTO
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the TorrentDTO interface.
 */
export function instanceOfTorrentDTO(value: object): value is TorrentDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('likes' in value) || value['likes'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function TorrentDTOFromJSON(json: any): TorrentDTO {
    return TorrentDTOFromJSONTyped(json, false);
}

export function TorrentDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TorrentDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'user': UserDTOFromJSON(json['user']),
        'likes': json['likes'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function TorrentDTOToJSON(json: any): TorrentDTO {
    return TorrentDTOToJSONTyped(json, false);
}

export function TorrentDTOToJSONTyped(value?: TorrentDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'user': UserDTOToJSON(value['user']),
        'likes': value['likes'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

