/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TorrentDTO } from './TorrentDTO';
import {
    TorrentDTOFromJSON,
    TorrentDTOFromJSONTyped,
    TorrentDTOToJSON,
    TorrentDTOToJSONTyped,
} from './TorrentDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface TorrentDTORequestResponse
 */
export interface TorrentDTORequestResponse {
    /**
     * 
     * @type {TorrentDTO}
     * @memberof TorrentDTORequestResponse
     */
    readonly response?: TorrentDTO | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof TorrentDTORequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the TorrentDTORequestResponse interface.
 */
export function instanceOfTorrentDTORequestResponse(value: object): value is TorrentDTORequestResponse {
    return true;
}

export function TorrentDTORequestResponseFromJSON(json: any): TorrentDTORequestResponse {
    return TorrentDTORequestResponseFromJSONTyped(json, false);
}

export function TorrentDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TorrentDTORequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : TorrentDTOFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function TorrentDTORequestResponseToJSON(json: any): TorrentDTORequestResponse {
    return TorrentDTORequestResponseToJSONTyped(json, false);
}

export function TorrentDTORequestResponseToJSONTyped(value?: Omit<TorrentDTORequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

