/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TorrentDTO } from './TorrentDTO';
import {
    TorrentDTOFromJSON,
    TorrentDTOFromJSONTyped,
    TorrentDTOToJSON,
    TorrentDTOToJSONTyped,
} from './TorrentDTO';

/**
 * 
 * @export
 * @interface TorrentDTOPagedResponse
 */
export interface TorrentDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof TorrentDTOPagedResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof TorrentDTOPagedResponse
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof TorrentDTOPagedResponse
     */
    totalCount: number;
    /**
     * 
     * @type {Array<TorrentDTO>}
     * @memberof TorrentDTOPagedResponse
     */
    data: Array<TorrentDTO>;
}

/**
 * Check if a given object implements the TorrentDTOPagedResponse interface.
 */
export function instanceOfTorrentDTOPagedResponse(value: object): value is TorrentDTOPagedResponse {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function TorrentDTOPagedResponseFromJSON(json: any): TorrentDTOPagedResponse {
    return TorrentDTOPagedResponseFromJSONTyped(json, false);
}

export function TorrentDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TorrentDTOPagedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(TorrentDTOFromJSON)),
    };
}

export function TorrentDTOPagedResponseToJSON(json: any): TorrentDTOPagedResponse {
    return TorrentDTOPagedResponseToJSONTyped(json, false);
}

export function TorrentDTOPagedResponseToJSONTyped(value?: TorrentDTOPagedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': ((value['data'] as Array<any>).map(TorrentDTOToJSON)),
    };
}

